### ISSUE TITLE
Plugin install FAILED, please fix bug!!!

### ISSUE THREAD

**Issue by ragcsalo** [tgardner/cordova-androidwear#7] opened 2015-11-22 12:50 UTC
Please fix the plugin installation package!!!

Fetching plugin "net.trentgardner.cordova.androidwear" via cordova plugins regis
try
npm http GET http://cordova.iriscouch.com/registry/_design/app/_rewrite/net.tren
tgardner.cordova.androidwear/-/net.trentgardner.cordova.androidwear-0.0.3.tgz
npm ERR! fetch failed http://cordova.iriscouch.com/registry/_design/app/_rewrite
/net.trentgardner.cordova.androidwear/-/net.trentgardner.cordova.androidwear-0.0
.3.tgz

**Comment by ragcsalo** [comment] 2015-11-22 13:49
Oh, I could install it like this:
cordova plugin add https://github.com/tgardner/cordova-androidwear

So please update the documentation, and recommend this install method! :-)

**Comment by tgardner** [comment] 2015-12-07 23:55
Duplicate of #6

**Closed as completed by tgardner** 2015-12-07 23:55 UTC
Labels: duplicate
